### ISSUE TITLE
[Bug]: BRAT said "No main.js file present"

### ISSUE THREAD

**Issue by nerisal** [Stackclash/obsidian-ttrpg-audio-manager#30]
### Description

I just followed the instructions on the installation page. But as soon as I paste the link this message from BRAT appears: 

> BRAT
> Stackclash/obsidian-ttrpg-audio-manager
> The release is not complete and cannot be download. main.js is missing from the Release

### Reproduction Steps

1. Launch Obsidian and open your vault.
2. Navigate to the BRAT settings and click Add Beta Plugin
3. In the input that appears paste https://github.com/Stackclash/obsidian-ttrpg-audio-manager and click Add Plugin.

### Expected Behavior

I expected to see the beta plugin installed just fine. 

### Version

0.1.0

### What version of Obsidian are you using?

1.6.7 (Latest)

**Comment by Stackclash** [comment]
I'm sorry but the plugin is still in development. I haven’t released the initial version. I'll make sure to add something to the README so people know.
